services:
  chatbot-ui:
    build:
      context: ./apps/chatbot_ui
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/chatbot_ui/src:/app/src

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./apps/api/src:/app/src

  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=langgraph_db
      - POSTGRES_USER=langgraph_user
      - POSTGRES_PASSWORD=langgraph_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - ./postgress_data:/var/lib/postgresql/data

  items-mcp-server:
    build:
      context: ./apps/items_mcp_server
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    env_file:
      - .env
    restart: unless-stopped

  reviews-mcp-server:
    build:
      context: ./apps/reviews_mcp_server
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    env_file:
      - .env
    restart: unless-stopped
